version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - PORT=3001
    volumes:
      - ./prisma:/app/prisma
      - ./dev.db:/app/dev.db
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=courtroom
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Alternative SQLite setup (if you prefer SQLite)
  app-sqlite:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - PORT=3001
    volumes:
      - ./prisma:/app/prisma
      - ./dev.db:/app/dev.db
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
